Adding php-cs-fixer
3liz/lizmap-gobs-module pull request #6
Opened 2021-01-21 09:47 UTC by drillinP

* Ticket : #2 
*  Adding php-cs-fixer as Github action

2021-01-21 09:54 UTC, Gustry reviewed
Can you add the makefile commands as well ? 
I will let a PHP dev review this PR.

2021-01-21 09:54 UTC, Gustry commented on .github/workflows/test-lint-php.yml
> +
It should be an empty line at the end of a file.

2021-01-21 14:21 UTC, rldhont requested changes
Just a quick fix before merge

2021-01-21 14:21 UTC, rldhont commented on .github/workflows/test-lint-php.yml
> +        args: --config=.php_cs.dist --allow-risky=yes --dry-run --diff
It should be an empty line at the end of a file.

2021-01-21 16:23 UTC, rldhont approved these changes

2021-04-07 11:37 UTC, mdouchin commented
I manually ran the make command, and added more commits since this PR. @drillinP could you please rebase over master and push force this branch please ?

2021-04-07 12:47 UTC, drillinP commented
@mdouchin j'ai fais le rebase

2022-10-13 13:13 UTC, Gustry commented
This has been done

2022-10-13 13:13 UTC, closed without merging